In [1]:
#This is the code for SVM 

In [2]:
import pandas as pd
import numpy as np
import os
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report

In [3]:
train_files = [
    "One-Hot/Train_Orig_OH.csv",
    "One-Hot/Scaled/Train_Scaled_Cont_OH.csv",
    "One-Hot/MinMax/Train_MM_OH.csv",
    "One-Hot/MinMax/train_OH_MM_PCA15.csv",
    "One-Hot/MinMax/train_OH_MM_PCA20.csv",
    "One-Hot/MinMax/train_OH_MM_PCA25.csv",
    "One-Hot/MinMax/train_OH_MM_PCA30.csv",
    "One-Hot/MinMax/train_OH_MM_PCA35.csv",
    "IntClasses/Train_Orig_Int.csv",
    "IntClasses/Scaled/Train_Scaled_Cont_Int.csv",
    "IntClasses/MinMax/Train_MM_Int.csv",
    "IntClasses/MinMax/train_Int_MM_PCA10.csv",
    "IntClasses/MinMax/train_Int_MM_PCA15.csv",
    "IntClasses/MinMax/train_Int_MM_PCA20.csv",
    "IntClasses/MinMax/train_Int_MM_PCA25.csv",
]

In [4]:
#First up lets start with Polynomial Kernel SVM 
#(we won't do linear as data is complex and not linearly separable)

In [5]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report

def evaluate_metrics(y_true, y_pred, set_name):
    print(f"Performance Metrics on {set_name} Data:")
    cm = confusion_matrix(y_true, y_pred)
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average='binary', pos_label=1)
    rec = recall_score(y_true, y_pred, average='binary', pos_label=1)
    f1 = f1_score(y_true, y_pred, average='binary', pos_label=1)

    print("Confusion Matrix:")
    print(cm)
    print(f"Accuracy: {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall: {rec:.4f}")
    print(f"F1-score: {f1:.4f}")
    print("Classification Report:")
    print(classification_report(y_true, y_pred))
    print("-" * 50)

    return acc, prec, rec, f1


In [6]:
#i. Polynomial Kernel SVM
from sklearn.svm import SVC

results = []

for path in train_files:
    print("\n" + "="*80)
    print(f"Processing dataset: {path}")
    
    train_df = pd.read_csv(path)
    valid_path = path.replace("Train", "Valid").replace("train", "valid")
    test_path = path.replace("Train", "Test").replace("train", "test")

    valid_df = pd.read_csv(valid_path)
    test_df = pd.read_csv(test_path)

    
    target_col = -2

    X_train = train_df.iloc[:, :target_col]
    y_train = train_df.iloc[:, target_col]

    X_valid = valid_df.iloc[:, :target_col]
    y_valid = valid_df.iloc[:, target_col]

    X_test = test_df.iloc[:, :target_col]
    y_test = test_df.iloc[:, target_col]

    # Train RBF SVM
    model = SVC(kernel='poly', C=1.0, gamma='scale')
    model.fit(X_train, y_train)

    name = os.path.basename(path)
    evaluate_metrics(y_valid, model.predict(X_valid), "Validation")
    acc, prec, rec, f1 = evaluate_metrics(y_test, model.predict(X_test), "Test")


    results.append({
        "Dataset": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1": f1
    })

# Final result summary
results_df = pd.DataFrame(results)
results_df



Processing dataset: One-Hot/Train_Orig_OH.csv
Performance Metrics on Validation Data:
Confusion Matrix:
[[2962   82]
 [ 444  512]]
Accuracy: 0.8685
Precision: 0.8620
Recall: 0.5356
F1-score: 0.6606
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      3044
           1       0.86      0.54      0.66       956

    accuracy                           0.87      4000
   macro avg       0.87      0.75      0.79      4000
weighted avg       0.87      0.87      0.86      4000

--------------------------------------------------
Performance Metrics on Test Data:
Confusion Matrix:
[[2960   84]
 [ 445  511]]
Accuracy: 0.8678
Precision: 0.8588
Recall: 0.5345
F1-score: 0.6589
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.97      0.92      3044
           1       0.86      0.53      0.66       956

    accuracy                           0.87      4000
   macro avg 

C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Test Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

         0.0       0.76      1.00      0.86      3044
         1.0       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------

Processing dataset: One-Hot/MinMax/train_OH_MM_PCA15.csv


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Validation Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      3044
           1       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Test Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      3044
           1       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------

Processing dataset: One-Hot/MinMax/train_OH_MM_PCA20.csv


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Validation Data:
Confusion Matrix:
[[2999   45]
 [ 922   34]]
Accuracy: 0.7582
Precision: 0.4304
Recall: 0.0356
F1-score: 0.0657
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.99      0.86      3044
           1       0.43      0.04      0.07       956

    accuracy                           0.76      4000
   macro avg       0.60      0.51      0.46      4000
weighted avg       0.68      0.76      0.67      4000

--------------------------------------------------
Performance Metrics on Test Data:
Confusion Matrix:
[[3010   34]
 [ 924   32]]
Accuracy: 0.7605
Precision: 0.4848
Recall: 0.0335
F1-score: 0.0626
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.99      0.86      3044
           1       0.48      0.03      0.06       956

    accuracy                           0.76      4000
   macro avg       0.62      0.51      0.46      4000
weight

C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Test Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

         0.0       0.76      1.00      0.86      3044
         1.0       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------

Processing dataset: IntClasses/MinMax/train_Int_MM_PCA10.csv


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Validation Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      3044
           1       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Test Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      3044
           1       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------

Processing dataset: IntClasses/MinMax/train_Int_MM_PCA15.csv


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Validation Data:
Confusion Matrix:
[[2937  107]
 [ 613  343]]
Accuracy: 0.8200
Precision: 0.7622
Recall: 0.3588
F1-score: 0.4879
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      3044
           1       0.76      0.36      0.49       956

    accuracy                           0.82      4000
   macro avg       0.79      0.66      0.69      4000
weighted avg       0.81      0.82      0.79      4000

--------------------------------------------------
Performance Metrics on Test Data:
Confusion Matrix:
[[2931  113]
 [ 598  358]]
Accuracy: 0.8223
Precision: 0.7601
Recall: 0.3745
F1-score: 0.5018
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      3044
           1       0.76      0.37      0.50       956

    accuracy                           0.82      4000
   macro avg       0.80      0.67      0.70      4000
weight

Dataset  Accuracy  Precision    Recall        F1
0           Train_Orig_OH.csv   0.86775   0.858824  0.534519  0.658930
1    Train_Scaled_Cont_OH.csv   0.94200   0.948020  0.801255  0.868481
2             Train_MM_OH.csv   0.76100   0.000000  0.000000  0.000000
3       train_OH_MM_PCA15.csv   0.76100   0.000000  0.000000  0.000000
4       train_OH_MM_PCA20.csv   0.76050   0.484848  0.033473  0.062622
5       train_OH_MM_PCA25.csv   0.77550   0.629464  0.147490  0.238983
6       train_OH_MM_PCA30.csv   0.86675   0.791724  0.600418  0.682927
7       train_OH_MM_PCA35.csv   0.90050   0.881148  0.674686  0.764218
8          Train_Orig_Int.csv   0.86850   0.858333  0.538703  0.661954
9   Train_Scaled_Cont_Int.csv   0.93600   0.928922  0.792887  0.855530
10           Train_MM_Int.csv   0.76100   0.000000  0.000000  0.000000
11     train_Int_MM_PCA10.csv   0.76100   0.000000  0.000000  0.000000
12     train_Int_MM_PCA15.csv   0.82225   0.760085  0.374477  0.501752
13     train_Int_MM_PCA20.csv   0.86225   0.792208  0.574268  0.665858
14     train_Int_MM_PCA25.csv   0.90700   0.871501  0.716527  0.786452

In [7]:
# Final result summary of Polynomial Kernel SVM
results_df = pd.DataFrame(results)
results_df
#note that these are for the test data

Dataset  Accuracy  Precision    Recall        F1
0           Train_Orig_OH.csv   0.86775   0.858824  0.534519  0.658930
1    Train_Scaled_Cont_OH.csv   0.94200   0.948020  0.801255  0.868481
2             Train_MM_OH.csv   0.76100   0.000000  0.000000  0.000000
3       train_OH_MM_PCA15.csv   0.76100   0.000000  0.000000  0.000000
4       train_OH_MM_PCA20.csv   0.76050   0.484848  0.033473  0.062622
5       train_OH_MM_PCA25.csv   0.77550   0.629464  0.147490  0.238983
6       train_OH_MM_PCA30.csv   0.86675   0.791724  0.600418  0.682927
7       train_OH_MM_PCA35.csv   0.90050   0.881148  0.674686  0.764218
8          Train_Orig_Int.csv   0.86850   0.858333  0.538703  0.661954
9   Train_Scaled_Cont_Int.csv   0.93600   0.928922  0.792887  0.855530
10           Train_MM_Int.csv   0.76100   0.000000  0.000000  0.000000
11     train_Int_MM_PCA10.csv   0.76100   0.000000  0.000000  0.000000
12     train_Int_MM_PCA15.csv   0.82225   0.760085  0.374477  0.501752
13     train_Int_MM_PCA20.csv   0.86225   0.792208  0.574268  0.665858
14     train_Int_MM_PCA25.csv   0.90700   0.871501  0.716527  0.786452

In [8]:
#verifying if C=1 is the best choice (it is!)
for c in [0.1, 1, 10]:
    model = SVC(kernel='rbf', C=c, gamma='scale')
    model.fit(X_train, y_train)
    acc = accuracy_score(y_valid, model.predict(X_valid))
    print(f"C={c}, Accuracy={acc:.4f}")

C=0.1, Accuracy=0.8912
C=1, Accuracy=0.9450
C=10, Accuracy=0.9423


In [9]:
#ii. Now for the RBF (Gaussian) Kernel SVM
from sklearn.svm import SVC

results = []

for path in train_files:
    print("\n" + "="*80)
    print(f"Processing dataset: {path}")
    
    train_df = pd.read_csv(path)
    valid_path = path.replace("Train", "Valid").replace("train", "valid")
    test_path = path.replace("Train", "Test").replace("train", "test")

    valid_df = pd.read_csv(valid_path)
    test_df = pd.read_csv(test_path)

    target_col = -2

    X_train = train_df.iloc[:, :target_col]
    y_train = train_df.iloc[:, target_col]

    X_valid = valid_df.iloc[:, :target_col]
    y_valid = valid_df.iloc[:, target_col]

    X_test = test_df.iloc[:, :target_col]
    y_test = test_df.iloc[:, target_col]

    # Train RBF SVM
    model = SVC(kernel='rbf', C=1.0, gamma='scale')
    model.fit(X_train, y_train)

    name = os.path.basename(path)
    evaluate_metrics(y_valid, model.predict(X_valid), "Validation")
    acc, prec, rec, f1 = evaluate_metrics(y_test, model.predict(X_test), "Test")


    results.append({
        "Dataset": name,
        "Accuracy": acc,
        "Precision": prec,
        "Recall": rec,
        "F1": f1
    })

# Final result summary
results_df = pd.DataFrame(results)
results_df



Processing dataset: One-Hot/Train_Orig_OH.csv
Performance Metrics on Validation Data:
Confusion Matrix:
[[2893  151]
 [ 335  621]]
Accuracy: 0.8785
Precision: 0.8044
Recall: 0.6496
F1-score: 0.7188
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.95      0.92      3044
           1       0.80      0.65      0.72       956

    accuracy                           0.88      4000
   macro avg       0.85      0.80      0.82      4000
weighted avg       0.87      0.88      0.87      4000

--------------------------------------------------
Performance Metrics on Test Data:
Confusion Matrix:
[[2897  147]
 [ 335  621]]
Accuracy: 0.8795
Precision: 0.8086
Recall: 0.6496
F1-score: 0.7204
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.95      0.92      3044
           1       0.81      0.65      0.72       956

    accuracy                           0.88      4000
   macro avg 

C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Test Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

         0.0       0.76      1.00      0.86      3044
         1.0       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------

Processing dataset: One-Hot/MinMax/train_OH_MM_PCA15.csv


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Validation Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      3044
           1       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Test Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      3044
           1       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------

Processing dataset: One-Hot/MinMax/train_OH_MM_PCA20.csv


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Validation Data:
Confusion Matrix:
[[3012   32]
 [ 933   23]]
Accuracy: 0.7588
Precision: 0.4182
Recall: 0.0241
F1-score: 0.0455
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.99      0.86      3044
           1       0.42      0.02      0.05       956

    accuracy                           0.76      4000
   macro avg       0.59      0.51      0.45      4000
weighted avg       0.68      0.76      0.67      4000

--------------------------------------------------
Performance Metrics on Test Data:
Confusion Matrix:
[[3030   14]
 [ 927   29]]
Accuracy: 0.7648
Precision: 0.6744
Recall: 0.0303
F1-score: 0.0581
Classification Report:
              precision    recall  f1-score   support

           0       0.77      1.00      0.87      3044
           1       0.67      0.03      0.06       956

    accuracy                           0.76      4000
   macro avg       0.72      0.51      0.46      4000
weight

C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Test Data:
Confusion Matrix:
[[3044    0]
 [ 956    0]]
Accuracy: 0.7610
Precision: 0.0000
Recall: 0.0000
F1-score: 0.0000
Classification Report:
              precision    recall  f1-score   support

         0.0       0.76      1.00      0.86      3044
         1.0       0.00      0.00      0.00       956

    accuracy                           0.76      4000
   macro avg       0.38      0.50      0.43      4000
weighted avg       0.58      0.76      0.66      4000

--------------------------------------------------

Processing dataset: IntClasses/MinMax/train_Int_MM_PCA10.csv


C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\aariz\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(

Performance Metrics on Validation Data:
Confusion Matrix:
[[3033   11]
 [ 947    9]]
Accuracy: 0.7605
Precision: 0.4500
Recall: 0.0094
F1-score: 0.0184
Classification Report:
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      3044
           1       0.45      0.01      0.02       956

    accuracy                           0.76      4000
   macro avg       0.61      0.50      0.44      4000
weighted avg       0.69      0.76      0.66      4000

--------------------------------------------------
Performance Metrics on Test Data:
Confusion Matrix:
[[3035    9]
 [ 947    9]]
Accuracy: 0.7610
Precision: 0.5000
Recall: 0.0094
F1-score: 0.0185
Classification Report:
              precision    recall  f1-score   support

           0       0.76      1.00      0.86      3044
           1       0.50      0.01      0.02       956

    accuracy                           0.76      4000
   macro avg       0.63      0.50      0.44      4000
weight

Dataset  Accuracy  Precision    Recall        F1
0           Train_Orig_OH.csv   0.87950   0.808594  0.649582  0.720418
1    Train_Scaled_Cont_OH.csv   0.96200   0.932258  0.906904  0.919406
2             Train_MM_OH.csv   0.76100   0.000000  0.000000  0.000000
3       train_OH_MM_PCA15.csv   0.76100   0.000000  0.000000  0.000000
4       train_OH_MM_PCA20.csv   0.76475   0.674419  0.030335  0.058058
5       train_OH_MM_PCA25.csv   0.78175   0.687783  0.158996  0.258284
6       train_OH_MM_PCA30.csv   0.87825   0.814765  0.634937  0.713698
7       train_OH_MM_PCA35.csv   0.92650   0.926546  0.752092  0.830254
8          Train_Orig_Int.csv   0.87975   0.809648  0.649582  0.720836
9   Train_Scaled_Cont_Int.csv   0.95475   0.920738  0.887029  0.903570
10           Train_MM_Int.csv   0.76100   0.000000  0.000000  0.000000
11     train_Int_MM_PCA10.csv   0.76100   0.500000  0.009414  0.018480
12     train_Int_MM_PCA15.csv   0.83700   0.764808  0.459205  0.573856
13     train_Int_MM_PCA20.csv   0.87725   0.798460  0.650628  0.717003
14     train_Int_MM_PCA25.csv   0.94000   0.905896  0.835774  0.869423

In [11]:
# Final result summary of the RBF Kernel SVM
results_df = pd.DataFrame(results)
results_df


Dataset  Accuracy  Precision    Recall        F1
0           Train_Orig_OH.csv   0.87950   0.808594  0.649582  0.720418
1    Train_Scaled_Cont_OH.csv   0.96200   0.932258  0.906904  0.919406
2             Train_MM_OH.csv   0.76100   0.000000  0.000000  0.000000
3       train_OH_MM_PCA15.csv   0.76100   0.000000  0.000000  0.000000
4       train_OH_MM_PCA20.csv   0.76475   0.674419  0.030335  0.058058
5       train_OH_MM_PCA25.csv   0.78175   0.687783  0.158996  0.258284
6       train_OH_MM_PCA30.csv   0.87825   0.814765  0.634937  0.713698
7       train_OH_MM_PCA35.csv   0.92650   0.926546  0.752092  0.830254
8          Train_Orig_Int.csv   0.87975   0.809648  0.649582  0.720836
9   Train_Scaled_Cont_Int.csv   0.95475   0.920738  0.887029  0.903570
10           Train_MM_Int.csv   0.76100   0.000000  0.000000  0.000000
11     train_Int_MM_PCA10.csv   0.76100   0.500000  0.009414  0.018480
12     train_Int_MM_PCA15.csv   0.83700   0.764808  0.459205  0.573856
13     train_Int_MM_PCA20.csv   0.87725   0.798460  0.650628  0.717003
14     train_Int_MM_PCA25.csv   0.94000   0.905896  0.835774  0.869423